services:
  - type: web
    name: translator-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app/app.py --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
